FN-2: List of Card Carousell
zmkhtr/Pokemon-App pull request #11
Opened 2022-11-09 15:21 UTC by asa98

- Card List Screen Carousell
- Limit result to 10
- Loading when fetching data
- Error message when failed fetching data
- Pull to refresh

2022-11-11 13:17 UTC, zmkhtr requested changes

2022-11-11 13:17 UTC, zmkhtr commented on Pokemon App/Pokemon App/CardCollectionViewCell/CardCollectionViewCell.swift
> +}
Buat juga fungsi buat handle cancel download dan fungsi untuk deallocated already showed image from memory

2022-11-11 13:17 UTC, zmkhtr commented on Pokemon App/Pokemon App/CardListCollectionView/PokemonCardListLoader.swift
> +    private func transformJsonDataToMovieList(with data: Data) throws -> [PokemonCard] {
Haloo ini kenapa `ToMovieList` haha

2022-11-11 13:17 UTC, zmkhtr commented on Pokemon App/Pokemon App/CardListCollectionView/PokemonCardListLoader.swift
> +    func getMovieList(completion: @escaping (PokemonCardListResult) -> Void) {
Ini kenapa `getMovieList` ?

2022-11-11 13:17 UTC, zmkhtr commented on Pokemon App/Pokemon App/CardListViewController/CardListViewController.swift
> +        loader.getMovieList { result in
ini masih `getMovieList`

2022-11-11 13:17 UTC, zmkhtr commented on Pokemon App/Pokemon App/CardListViewController/CardListViewController.swift
> +            print(err)
Hapus print jika sudah tidak digunakan.

2022-11-11 13:17 UTC, zmkhtr commented on Pokemon App/Pokemon App/Data Model/PokemonCard.swift
> +let fakePokemonCard = PokemonCard(id: "123" , imageURL: "https://images.pokemontcg.io/swsh4/25_hires.png")
ini apaan? hapus saja jika tidak dipakai

2022-11-11 13:17 UTC, zmkhtr commented on Pokemon App/Pokemon App/ImageLoader.dart.swift
> +            }
Ini bisa disimplify jadi seperti ini 
```suggestion
            if let data = data,
                let image = UIImage(data: data),
                let response = response as? HTTPURLResponse,
                response.statusCode == 200 {
                
                DispatchQueue.main.sync {
                    completion(.success(image))
                }
            } else {
                completion(.failure)
            }
```

2022-11-11 13:17 UTC, zmkhtr commented on Pokemon App/Pokemon App/CardListCollectionView/PokemonCardListLoader.swift
> +                    completion(.success(movies))
force unwrap `data!` bisa menyebabkan Force Close. Lebih baik dibuat 
```suggestion
            if let data = data,
               let response = response as? HTTPURLResponse,
               response.statusCode == 200 {
                let movies = try self.transformJsonDataToMovieList(with: data)
            } else {
                completion(.failure("Unexpected Data"))
            }
```

2022-11-11 13:17 UTC, zmkhtr commented on Pokemon App/Pokemon App/CardListViewController/CardListViewController.swift
> +    private func setUPCardListCollectionView() {
setUp bukan setUP

2022-11-11 13:20 UTC, zmkhtr commented
![Simulator Screen Recording - iPhone 14 Pro Max - 2022-11-11 at 19 53 36](https://user-images.githubusercontent.com/33575723/201344597-1924126c-7f3a-4834-9ebe-7e3a474730b3.gif)

@asa98  Tolong fix ini, 
1. image blinking & imagenya keganti
2. Ketika scroll navigation/navbar jadi putih/grey (Seharusnya warnanya tetap sama tidak ada perubahan).
3. Force close saat diakses tanpa internet 

(cek code review)

2022-11-11 16:37 UTC, asa98 commented on Pokemon App/Pokemon App/CardCollectionViewCell/CardCollectionViewCell.swift
> +}
nge-cancel download gimana caranya? cancel url sessionnya?
fungsi deallocated maksudnya gimana mas?

2022-11-12 05:53 UTC, zmkhtr commented on Pokemon App/Pokemon App/CardCollectionViewCell/CardCollectionViewCell.swift
> +}
yg pokemonCardImageView.image = nil pas udah gak dibutuhin imagenya. Deallocated = hapus dari memory

2022-11-12 06:01 UTC, asa98 commented on Pokemon App/Pokemon App/CardCollectionViewCell/CardCollectionViewCell.swift
> +}
bukan di cancel download? kok aku nggak ngerti sih mas._.

2022-11-12 09:54 UTC, zmkhtr commented on Pokemon App/Pokemon App/CardCollectionViewCell/CardCollectionViewCell.swift
> +}
@asa98 bener cancel download. coba lu liat disini kan gue nyontohin juga bisa nge-nil image nya
https://github.com/Funios-community/Movie-App-Example/blob/main/Funios%20Animals/Cell/MovieCell.swift

2022-11-12 10:00 UTC, zmkhtr requested changes

2022-11-12 10:00 UTC, zmkhtr commented on Pokemon App/Pokemon App/CardCollectionViewCell/CardCollectionViewCell.swift
> +    }
ini hapus aja itu udha lu deallocated di cancel download

2022-11-12 11:43 UTC, zmkhtr approved these changes

2022-11-12 11:44 UTC, merged