Fn 0 agung
zmkhtr/Pokemon-App pull request #15
Opened 2022-11-12 11:04 UTC by jaygung17

https://trello.com/c/1AG5DXgG/49-fn-0-tabbar-controller

-Create Tab Bar controller
-Create Card List View Controller
-Create Favourites View Controller

2022-11-12 11:43 UTC, zmkhtr requested changes
![Screenshot 2022-11-12 at 18 42 30](https://user-images.githubusercontent.com/33575723/201472365-611013dc-8027-453d-952c-d6fb529fc497.png)

Warna background tabbar nya belum sesuai figma.

2022-11-12 11:43 UTC, zmkhtr commented on Pokemon App/Pokemon App/PokemonTabBarController/PokemonTabBarController.swift
> +        tabBar.unselectedItemTintColor = .white
Jika lu menggunakan xib/storyboard sebisa mungkin custom di xib/storyboard nya jangan digabung sama programatically kalau masih bisa di lakukan di storyboard/xib nya.

2022-11-12 12:00 UTC, jaygung17 commented on Pokemon App/Pokemon App/PokemonTabBarController/PokemonTabBarController.swift
> +        tabBar.unselectedItemTintColor = .white
oh baik mas azam sebentar Aku coba dulu, ini kalo diperbaikin Aku commit push denagn ticket FN 1 app kah? nanti Aku kasih keterangan revisi background tabbar yang belum sesuai ya.. Terima kasih mas Azam

2022-11-12 12:04 UTC, zmkhtr commented on Pokemon App/Pokemon App/PokemonTabBarController/PokemonTabBarController.swift
> +        tabBar.unselectedItemTintColor = .white
lah jangan FN1 dulu ini FN0 belum selesai, selesaiin dulu nanti ini klo FN0 udah di approve+merger ke branch `Agung` baru lu new branch lagi dari branch `Agung` buat yg FN1. jadi terupdate kode lu. 

Kalau lu mau langsung'' gitu ada kemungkinan conflict lebih besar, nanti bakal lebih susah kedepannya
@jaygung17

2022-11-12 12:05 UTC, jaygung17 commented on Pokemon App/Pokemon App/PokemonTabBarController/PokemonTabBarController.swift
> +        tabBar.unselectedItemTintColor = .white
baik mas azam, makasih banyak.. baru pertama ini pake GitHub...

2022-11-12 12:19 UTC, jaygung17 commented
Revisi translucent dan tint color dari programmatically ke storyboard configuration

2022-11-12 14:35 UTC, zmkhtr requested changes
![simulator_screenshot_66A6900A-B76B-41AB-818D-ED7306D55E57](https://user-images.githubusercontent.com/33575723/201479018-a1472084-f266-47ff-af3f-34ae4cad0501.png)

Masih salah dan itu kenapa ada navbar "Card List" di tengah'' screen?

2022-11-12 14:35 UTC, zmkhtr commented on Pokemon App/Pokemon App/PokemonTabBarController/PokemonTabBarController.swift
> +}
Klo gak dipakai hapus saja filenya

2022-11-15 13:43 UTC, zmkhtr commented
![Screenshot 2022-11-15 at 20 43 00](https://user-imag@jaygung17 .githubusercontent.com/33575723/201934352-002ddba7-20f7-4818-94ae-a17c0ca5dc41.png)
@jaygung17 tolong rubah nama colornya jadi yang human readable

2022-11-15 13:54 UTC, zmkhtr commented
![Screenshot 2022-11-15 at 20 54 02](https://user-images.githubusercontent.com/33575723/201936801-255f7e64-9aa8-43f6-9367-3ec8bd6ab379.png)
@jaygung17 ini gabisa dirun dan ada kode yang seharusnya gak di FN-0. Tolong dibenerkan dan di PR sesuai tiket.

2022-11-15 14:10 UTC, jaygung17 commented
udah bisa di run ya mas azam? ku comment yang tidak perlu. Minta tolong korekei untuk FN-1 nya ya mas.. makasih mas azam

2022-11-15 14:11 UTC, zmkhtr requested changes
Tolong PR sesuai Tiket!

2022-11-15 14:11 UTC, zmkhtr commented on Pokemon App/Pokemon App/CardListController/CardListController.swift
> +    let searchController = UISearchController()
Ini apaan? hapus saja kalau gak dipakai

2022-11-15 14:11 UTC, zmkhtr commented on Pokemon App/Pokemon App/CardListController/CardListController.swift
> +    }
Indentationnya tolong di rapihin
```suggestion
class CardListViewController: UIViewController, UICollectionViewDelegate {
    
    @IBOutlet weak var cardListCollectionView: UICollectionView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        navigationItem.searchController = searchController
    }
        
}
```

2022-11-15 14:11 UTC, zmkhtr commented on Pokemon App/Pokemon App/Data Model/QTPokemonCardsModel.swift
> +}
Ini bukan di FN-0 hapus aja kalau belum dipakai. tolong PR sesuai Tiket.

2022-11-15 14:11 UTC, zmkhtr commented on Pokemon App/Pokemon App/FavouritesViewController/FavouritesViewController.swift
> +    let searchController = UISearchController()
ini apaan? hapus saja kalagak dipakai

2022-11-15 14:11 UTC, zmkhtr commented on Pokemon App/Pokemon App/PokemonTabBarController/PokemonTabBarController.swift
> +}
Kalau gak dipakai hapus saja file ini.

2022-11-15 14:11 UTC, zmkhtr commented on Pokemon App/Pokemon App/CardListController/PokemonLoader.swift
> +//}
Kalau gak kepakai hapus saja jangan dikomen kyk gini

2022-11-15 14:11 UTC, zmkhtr commented on Pokemon App/Pokemon App/CardsCollectionView/CardCollectionViewCell.swift
> +    override func awakeFromNib() {
Indentationnya tolong rapihin dan penamaan variabel tolong yang lebih deskriptif
```suggestion
    @IBOutlet weak var pokemonImageView: UIImageView!
    
    override func awakeFromNib() {
```

2022-11-15 14:11 UTC, zmkhtr commented on Pokemon App/Pokemon App/Data Model/PokemonCardsModel.swift
> +
Ini bukan di FN-0 hapus aja kalau belum dipakai. tolong PR sesuai Tiket.

2022-11-15 14:35 UTC, zmkhtr commented on Pokemon App/Pokemon App/CardListController/CardListController.swift
> +    }
@jaygung17 ini tolong benerin juga

2022-11-15 14:35 UTC, zmkhtr commented on Pokemon App/Pokemon App/PokemonTabBarController/PokemonTabBarController.swift
> +}
@jaygung17 ini tolong hapus aja klo gak dipakai

2022-11-15 14:46 UTC, zmkhtr approved these changes

2022-11-15 14:48 UTC, merged

2022-11-15 17:21 UTC, jaygung17 commented on Pokemon App/Pokemon App/CardsCollectionView/CardCollectionViewCell.swift
> +    override func awakeFromNib() {
oh okay itu pokemonCardImageView gitu ya biar lebih jelas