Darin-FN-3
zmkhtr/Pokemon-App pull request #17
Opened 2022-11-12 15:46 UTC by asa98

2022-11-12 15:47 UTC, asa98 commented
pusing benerin konflik nya, ulang aja ya mas._.

2022-11-15 13:52 UTC, zmkhtr requested changes

2022-11-15 13:52 UTC, zmkhtr commented on Pokemon App/Pokemon App/CardListViewController/CardListViewController.swift
> +    }
figmanya udah gue update tolong cek tiketnya lagi https://trello.com/c/EE3RSEqF/35-fn-3-category-list

2022-11-15 13:52 UTC, zmkhtr commented on Pokemon App/Pokemon App/CategoryListCollectionView/CategoryListLoader.swift
> +            }
`DispatchQueue.main.sync` ini sebenernya bisa lu hapus dari sini. karena gue liat lu udah dispatch ke main pas binding view nya contohnya di fungsi `successLoadCategories` yg lu bikin itu jadi gak perlu 2x

2022-11-23 13:03 UTC, zmkhtr approved these changes

2022-11-23 13:03 UTC, merged