FN-0 TabBar controller
zmkhtr/Pokemon-App pull request #20
Opened 2022-11-20 15:00 UTC by Septianadwi

2022-11-23 13:47 UTC, zmkhtr requested changes
Halo @Septianadwi FN-0 itu simple bikin tab-bar dengan 2 VC kosong didalamnnya, lu terlalu banyak komponen yang belum diperlukan, tolong dihapus saja.
![Screenshot 2022-11-23 at 20 46 02](https://user-images.githubusercontent.com/33575723/203562414-0467fddf-ae9e-4124-9e42-33862d1e84cc.png)
Dan desain tabbarnya masih belum seperti figma. tolong diperbaiki
![Screenshot 2022-11-23 at 20 47 11](https://user-images.githubusercontent.com/33575723/203562671-18537b5d-14db-4ff9-b152-e0428029fc4c.png)

2022-11-27 19:59 UTC, Septianadwi commented
ok mas, udah saya rubah.

2022-11-27 21:03 UTC, Septianadwi commented
Mas mau nanya, title yang favorite sama cardlist make navigationcontroller ya mas terus di jadiian view controller? soalny ga sampe atas warna nya kalo make view controller.

2022-12-03 06:26 UTC, zmkhtr approved these changes

2022-12-03 06:26 UTC, merged