Add networking and configure navbar and tabbar bacground when scrolling
zmkhtr/Pokemon-App pull request #23
Opened 2022-11-20 18:43 UTC by Fostahh

2022-11-23 14:38 UTC, zmkhtr requested changes
Untuk function/variable/etc yang hanya dipakai di-class tersebut gunakan access control private.

Note: design pattern yg lu pakai agak beda, mungkin nanti bisa diobrolin khusus. untuk sekarang oke aja, lanjutkan.

2022-11-23 14:38 UTC, zmkhtr commented on Pokemon App/Pokemon App/Core/Utils/ObjectMapper.swift
> +    func mapListPokemonResponseToListPokemonDomain(listPokemonResponse: [PokemonResponse]) -> [Pokemon] {
ini bisa lu bikin static aja, karena lu gabutuh instance dari ObjectMapper class ini cuma sabagai namespace aja. 
```suggestion
    static func mapListPokemonResponseToListPokemonDomain(listPokemonResponse: [PokemonResponse]) -> [Pokemon] {
```

2022-11-23 14:38 UTC, zmkhtr commented on Pokemon App/Pokemon App/Core/Data Source/Remote/Loader/PokemonLoader.swift
> +        }.resume()
Ini jangan lupa di weakify [weak self] agar bisa dideallocated dari memory saat sudah tidak dibutuhkan.
Object mapper bisa dibuat static jadi gaperlu bikin instance nya `ObjectMapper()` X.
Ini approach yg better untuk memastikan data dan response tidak nil.
```suggestion
        URLSession.shared.dataTask(with: url) { [weak self] (data, response, error) in
        guard let self = self else { return }
            DispatchQueue.main.async {
                completion(.loading(false))
                
                do {
                 if let data = data,
                       let response = response as? HTTPURLResponse,
                       response.statusCode == 200 {
                    let result = try JSONDecoder().decode(ListPokemonResponse.self, from: data)
                    let response = ObjectMapper.mapListPokemonResponseToListPokemonDomain(listPokemonResponse: result.data)

                        completion(.success(response))
                    } else {
                        completion(.failure("Unexpected Data"))
                    }
                } catch let error {
                    let errorMessage = error.localizedDescription
                    completion(.failure(errorMessage))
                }
            }
        }.resume()
```

2022-11-23 14:38 UTC, zmkhtr commented on Pokemon App/Pokemon App/Core/Data Source/Remote/Loader/PokemonLoader.swift
> +        let url = URL(string: "https://api.pokemontcg.io/v2/cards?page=\(currentPage)&pageSize=\(pageSize)")!
Selain di hardcode di URL bisa tambahin parameternya menggunakan `URLQueryItem`

2022-11-23 14:38 UTC, zmkhtr commented on Pokemon App/Pokemon App/Utils/Extension/UIImageView+Extension.swift
> +}
jangan buat extension buat imageLoader yang ngedownload dari URL dan bisa dicancel progress downloadnya.

2022-11-23 14:38 UTC, zmkhtr commented on Pokemon App/Pokemon App/UI/Reusable/View/ListPokemonView.swift
> +    }
size card lu masih terlalu lonjong tolong diperbaiki agar sama seperti figma.

2022-11-23 22:29 UTC, zmkhtr commented
Ada yg kurang tepat cara makai git lu nih. setiap gue pindah ke branch lu ada commitan yang belum dipush gini, tolong dibenerin dulu deh. @Fostahh 
<img width="1108" alt="Screenshot 2022-11-24 at 05 28 16" src="https://user-images.githubusercontent.com/33575723/203656594-99a6ad66-5703-4bb0-82d3-345245095d14.png">

2022-11-24 00:52 UTC, Fostahh commented
Di gua kok aman ya Bang?
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/70441512/203670633-c0cf52c5-001c-43e5-91f5-4731e4fcb360.png">

2022-11-24 00:54 UTC, Fostahh commented on Pokemon App/Pokemon App/Core/Utils/ObjectMapper.swift
> +    func mapListPokemonResponseToListPokemonDomain(listPokemonResponse: [PokemonResponse]) -> [Pokemon] {
gas Bang Kita diskusinya kapan ya?

2022-11-24 01:33 UTC, Fostahh commented on Pokemon App/Pokemon App/Core/Utils/ObjectMapper.swift
> +    func mapListPokemonResponseToListPokemonDomain(listPokemonResponse: [PokemonResponse]) -> [Pokemon] {
Tolong dicek kembali Bang sudah diperbaiki

2022-11-24 01:33 UTC, Fostahh commented on Pokemon App/Pokemon App/Core/Data Source/Remote/Loader/PokemonLoader.swift
> +        }.resume()
Tolong dicek kembali Bang sudah diperbaiki

2022-11-24 01:33 UTC, Fostahh commented on Pokemon App/Pokemon App/Utils/Extension/UIImageView+Extension.swift
> +}
Tolong dicek kembali Bang sudah diperbaiki

2022-11-24 01:33 UTC, Fostahh commented on Pokemon App/Pokemon App/UI/Reusable/View/ListPokemonView.swift
> +    }
Tolong dicek kembali Bang sudah diperbaiki

2022-11-24 01:33 UTC, Fostahh commented on Pokemon App/Pokemon App/Core/Data Source/Remote/Loader/PokemonLoader.swift
> +        let url = URL(string: "https://api.pokemontcg.io/v2/cards?page=\(currentPage)&pageSize=\(pageSize)")!
Tolong dicek kembali Bang sudah diperbaiki

2022-12-03 06:27 UTC, zmkhtr approved these changes

2022-12-03 06:27 UTC, closed without merging